WITH 
T AS (
    SELECT DISTINCT(CHILD.ID), CHILD.PARENT_ID
    FROM ECOLI_DATA PARENT
    JOIN ECOLI_DATA ME 
      ON PARENT.ID = ME.PARENT_ID
    JOIN ECOLI_DATA CHILD
      ON ME.ID = CHILD.PARENT_ID
    ORDER BY CHILD.ID ASC
)
SELECT PARENT.ID
FROM T PARENT
LEFT JOIN T CHILD 
  ON PARENT.PARENT_ID = CHILD.ID
WHERE CHILD.ID IS NULL
ORDER BY PARENT.ID ASC;