SELECT D.ID, COALESCE(T.COUNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA D
LEFT JOIN (
    SELECT PARENT.ID, COUNT(*) AS COUNT
    FROM ECOLI_DATA PARENT
    JOIN ECOLI_DATA CHILD 
      ON PARENT.ID = CHILD.PARENT_ID 
    GROUP BY PARENT.ID
) T
  ON D.ID = T.ID
ORDER BY D.ID ASC;