WITH 
ON_SALE AS (
    SELECT *
    FROM ONLINE_SALE
), 
OFF_SALE AS (
    SELECT OFFLINE_SALE_iD, NULL AS USER_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE
    FROM OFFLINE_SALE O
)

SELECT 
    DATE_FORMAT(T.SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
    T.PRODUCT_ID, 
    T.USER_ID,
    T.SALES_AMOUNT
FROM (
    SELECT *
    FROM ON_SALE 
    
    UNION ALL 
    
    SELECT *
    FROM OFF_SALE
) T
WHERE T.SALES_DATE >= '2022-03-01' AND T.SALES_DATE < '2022-04-01'
ORDER BY T.SALES_DATE ASC, T.PRODUCT_ID ASC, T.USER_ID ASC;