WITH DISCOUNT AS (
    SELECT 
        PLAN_ID, 
        CAR_TYPE, 
        CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) AS DURATION_TYPE,
        ROUND((100 - DISCOUNT_RATE) / 100, 2) AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
) 

SELECT *
FROM (
    SELECT 
        C.CAR_ID, 
        C.CAR_TYPE, 
        FLOOR(C.DAILY_FEE * (
            SELECT D.DISCOUNT_RATE
            FROM DISCOUNT D
            WHERE C.CAR_TYPE = D.CAR_TYPE
              AND D.DURATION_TYPE = 30
        ) * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
      AND NOT EXISTS (
          SELECT 1 
          FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H 
          WHERE H.CAR_ID = C.CAR_ID 
            AND (H.START_DATE <= '2022-11-30' AND H.END_DATE >= '2022-11-01')
      )
) T
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC;

# CAR_RENTAL_COMPANY_CAR
# CAR_RENTAL_COMPANY_RENTAL_HISTORY
# CAR_RENTAL_COMPANY_DISCOUNT_PLAN

# SELECT COUNT(*)
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE 