SELECT PARENT.FOOD_TYPE, PARENT.REST_ID, PARENT.REST_NAME, PARENT.FAVORITES
FROM REST_INFO PARENT
JOIN (
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
) CHILD 
  ON PARENT.FOOD_TYPE = CHILD.FOOD_TYPE AND PARENT.FAVORITES = CHILD.FAVORITES
ORDER BY PARENT.FOOD_TYPE DESC;