WITH 
_2021_BUY AS (
    SELECT YEAR(S.SALES_DATE) AS YEAR, MONTH(S.SALES_DATE) AS MONTH, COUNT(DISTINCT(U.USER_ID)) AS PURCHASED_USERS
    FROM USER_INFO U 
    JOIN ONLINE_SALE S
      ON U.USER_ID = S.USER_ID
    WHERE YEAR(U.JOINED) = 2021
    GROUP BY YEAR(S.SALES_DATE), MONTH(S.SALES_DATE)
), 
_2021_SIGNED AS (
    SELECT COUNT(*) AS TOTAL_USERS
    FROM USER_INFO U 
    WHERE YEAR(JOINED) = 2021
)

SELECT YEAR, MONTH, PURCHASED_USERS, ROUND(PURCHASED_USERS / TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM _2021_BUY 
CROSS JOIN _2021_SIGNED
ORDER BY YEAR ASC, MONTH ASC;