SELECT CONCAT(QUARTER_NUM, 'Q') AS QUARTER, COUNT(*) AS ECOLI_COUNT
FROM (
    SELECT ((MONTH(DIFFERENTIATION_DATE) - 1) DIV 3) + 1 AS QUARTER_NUM
    FROM ECOLI_DATA
) T
GROUP BY QUARTER_NUM
ORDER BY QUARTER_NUM;
