WITH DISCOUNT AS (
    SELECT 
        CAR_TYPE, 
        CAST(REPLACE(DURATION_TYPE, '일 이상', '') AS UNSIGNED) AS DURATION_TYPE, 
        (100 - DISCOUNT_RATE) / 100 AS DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
)
SELECT 
    H.HISTORY_ID,
    FLOOR(C.DAILY_FEE 
        * COALESCE(
            (SELECT D.DISCOUNT_RATE 
             FROM DISCOUNT D
             WHERE D.CAR_TYPE = C.CAR_TYPE
               AND (DATEDIFF(H.END_DATE, H.START_DATE) + 1) >= D.DURATION_TYPE
             ORDER BY D.DURATION_TYPE DESC
             LIMIT 1)
          , 1) 
        * (DATEDIFF(H.END_DATE, H.START_DATE) + 1)
    ) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, H.HISTORY_ID DESC;