SELECT FH.FLAVOR
FROM (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM
    FROM FIRST_HALF
    GROUP BY FLAVOR
) FH
JOIN (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS SUM
    FROM JULY 
    GROUP BY FLAVOR
) J
  ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.SUM + J.SUM) DESC
LIMIT 3;



