WITH RECURSIVE HOURS AS (
    SELECT 0 AS HOUR
    
    UNION ALL
    
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
)
SELECT H.HOUR, COALESCE(G.COUNT, 0) AS COUNT
FROM HOURS H
LEFT JOIN (
    SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT
    FROM ANIMAl_OUTS 
    GROUP BY HOUR(DATETIME)
) G
  ON H.HOUR = G.HOUR
ORDER BY HOUR ASC;

