SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R 
JOIN MEMBER_PROFILE P 
  ON R.MEMBER_ID = P.MEMBER_ID
JOIN (
    SELECT 
          MEMBER_ID, 
          RANK() OVER(ORDER BY COUNT(*) DESC) AS RNK
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
) T
  ON R.MEMBER_ID = T.MEMBER_ID
WHERE T.RNK = 1
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;