SELECT CHILD.ID, CHILD.GENOTYPE, PARENT.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA PARENT 
JOIN ECOLI_DATA CHILD 
  ON PARENT.ID = CHILD.PARENT_ID
WHERE (PARENT.GENOTYPE & CHILD.GENOTYPE) = PARENT.GENOTYPE
ORDER BY CHILD.ID ASC;